### ISSUE TITLE
Error on creating changelog

### ISSUE THREAD

**Issue by tirolerstefan** [tomasbjerre/git-changelog-bitbucket-plugin#13]
I tried to generate the changelog for one of our (quite big) repositories, but get an runtime exception in the log.

Git Changelog for Bitbucket v1.4 
Bitbucket v4.1.0

java.lang.RuntimeException: First commit at: 7e5583ff8d72b98e1b653691e618e1bc56d9c4a8
Refs: 
Ref: HEAD -> 88c88b2c1b4ddb2703fbe33fbada88cfa6ea4021
Ref: refs/heads/bugfix/BIB-100-blablabla -> 5edbd2b71b6b1c1e625a8798c12ab77b88ae1169
Ref: refs/heads/bugfix/BIB-867-testbug -> 75ecfeb237aea354b43e4ef0a0d906d1bf0b9717
Ref: refs/heads/bugfix/BIB-870-testmerge -> b959726c9f755432607f66924681bb2c9323312d
[...]

	at se.bjurr.gitchangelog.internal.git.GitRepo.getGitRepoData(GitRepo.java:93) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:345) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:315) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:332) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at se.bjurr.changelog.bitbucket.presentation.RestResource.getFromRefToRef(RestResource.java:91) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
	at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1446433820000.jar:na]
	at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-4.3.2_1446433820000.jar:na]
	at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-4.3.2_1446433820000.jar:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[bitbucket-service-impl-4.1.0.jar:na]
	at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
	... 218 frames trimmed
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: 92d9c58f639c35e=Ref[refs/tags/brrrrrrr=079f418696ee88e7e24f7a68a6f90c38c4d5e20d] and 92d9c58f639c35e=Ref[refs/tags/briii=a579b2e8f0efb3f443a899c32c10dd890cfab6d3]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
	at se.bjurr.gitchangelog.internal.git.GitRepo.gitTags(GitRepo.java:102) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	at se.bjurr.gitchangelog.internal.git.GitRepo.getGitRepoData(GitRepo.java:91) ~[plugin.8774517398436968055.git-changelog-for-bitbucket-1.4_1455518821000.jar:na]
	... 23 common frames omitted

**Comment by tomasbjerre** [comment]
You have tags brrrrrrr and briii pointing at the same commit right?

**Comment by tirolerstefan** [comment]
Yes, this was just for testing reasons, today.
After I deleted them, the exception doesn't occur, but I still have problems retrieving any content, still getting "Error :(", hmmm, no log lines.

**Comment by tomasbjerre** [comment]
Ok, I would suggest making some calls to the REST api to figure out whats going on.

**Comment by tirolerstefan** [comment]
Thanks for the hint with the REST api.

Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: 7e9798aa9aea794=Ref[refs/tags/uriel20151202-0708=8a9f58cc996a3860e5996af1fcbca7a9b755eb75] and 7e9798aa9aea794=Ref[refs/tags/patch/testtag=d2de43cbe68d6b59ca0f00171ff957ad2ac9cb62]

=> There were other tags on same commit, I deleted them (meanwhile) to get a changelog.

Now, I get a changelog using the REST API with following call:

`/rest/changelog/1.0/BIB/bibmaster/fromref/ambriel01/toref/ambriel07`

but no changelog on the repository page when calling.

`/plugins/servlet/repository/BIB/bibmaster#?from=build/ambriel01&to=build/ambriel07`

This returns "Error :(".

When I manually change the URL to ...

`/plugins/servlet/repository/BIB/bibmaster#?from=ambriel01&to=ambriel07`

... I get a changelog returned. Maybe a small problem with tag names containing sla

**Comment by tomasbjerre** [comment]
This should now be fixed in 1.5. Released to Marketplace. Note that slashes are encoded as `_slash_` now.

**Comment by tirolerstefan** [comment]
looks good, thanks for the fast release!

**Comment by deepak829125** [comment]
I am getting error : CHANGELOG.html not creating

Creating changelog CHANGELOG.htmljava.lang.IllegalArgumentException: Illegal URL: /
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:437)
	at se.bjurr.gitchangelog.internal.integrations.github.GitHubServiceFactory.getGitHubService(GitHubServiceFactory.java:61)
	at se.bjurr.gitchangelog.internal.issues.IssueParser.createGitHubClient(IssueParser.java:188)
	at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:59)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:462)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:77)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:99)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:168)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:27)
	at hudson.FilePath.act(FilePath.java:1162)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:37)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:50)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1878)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
