### ISSUE TITLE
Bitbucket -> Jira: Http Error 401

### ISSUE THREAD

**Issue by tirolerstefan** [tomasbjerre/git-changelog-bitbucket-plugin#15]
After trying successful on our test systems, I installed the plugin on our live bitbucket server which is connected to Jira using SSL.

Here I get an 401 exception. When I enter the URL https://jira.xxxx.com/rest/api/2/issue/DLA-911?fields=parent,summary in my same browser session, I get a valid result with return code 200.

2016-02-19 06:58:26,612 ERROR [http-nio-80-exec-9] emp000621 @KIQBHMx418x285211x2 wpmwu 10.10.16.85 "GET /rest/changelog/1.0/BIB/bib/fromref/build_slash_bib1539p01/toref/build_slash_bib1539p18 HTTP/1.1" s.b.g.i.integrations.rest.RestClient Got:
null
java.io.IOException: Server returned HTTP response code: 401 for URL: https://jira.xxxx.com/rest/api/2/issue/DLA-911?fields=parent,summary
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[na:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_60]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_60]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient.getResponse(RestClient.java:82) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient.doGet(RestClient.java:64) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient.access$000(RestClient.java:23) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient$1.load(RestClient.java:35) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient$1.load(RestClient.java:32) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) [guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) [guava-18.0.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient.get(RestClient.java:47) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.integrations.jira.JiraClient.getIssue(JiraClient.java:33) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:76) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:336) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:306) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:320) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at se.bjurr.changelog.bitbucket.presentation.RestResource.getFromRefToRef(RestResource.java:88) [plugin.5876010548689494348.git-changelog-for-bitbucket-1.5_1455806655000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1446433820000.jar:na]
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
	at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1446433820000.jar:na]
	at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-4.3.2_1446433820000.jar:na]
	at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-4.3.2_1446433820000.jar:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
	at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[bitbucket-service-impl-4.1.0.jar:na]
	at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
	... 218 frames trimmed

**Comment by tomasbjerre** [comment]
Should be fixed in 1.6.

**Comment by tirolerstefan** [comment]
Hmm, after upgrading to 1.6 / 1.7, I don't see a result.
REST API returns the JSON structure, but content ends before {{issues}} loop.
I don't see any debug info in logfile. Sorry, I can't help debugging this.

Tried with

# Git Changelog changelog

{{#commits}}
**{{{messageTitle}}}**

{{#messageBodyItems}}
 * {{.}} 
{{/messageBodyItems}}

[{{hash}}] {{authorName}} *{{commitTime}}*

{{/commits}}

On test server (same plugin, no SSL), I get valid values.

**Comment by tomasbjerre** [comment]
Is there a long responsetime? If so, do you get issues if you disable "Lookup Jira Titles" in admin GUI?

**Comment by tirolerstefan** [comment]
I tried it with and without "Lookup Jira Titles", now, no change.
I only used the {{commits}} loop.

The rest API call returns quickly, but when I click on button "Window", the browser shows and endless progress icon.

Could you give me a debug version with additional logging, maybe?

**Comment by tomasbjerre** [comment]
If you want to debug it you can have a look at the Travis-file:
https://github.com/tomasbjerre/git-changelog-bitbucket-plugin/blob/master/.travis.yml

It shows how to setup the environment with Atlassian SDK. Then you just run "mvn bitbucket:debug" and remote-debug with Eclipse or something.
