### ISSUE TITLE
Errors installing in 4.8.1

### ISSUE THREAD

**Issue by sundogit** [tomasbjerre/git-changelog-bitbucket-plugin#20]
We try installing from the marketplace and it says it can't enable and to refer to the logs. The logs show the following:

```
2016-07-25 14:47:40,714 ERROR [ThreadPoolAsyncTaskExecutor::Thread 45] asuda @1WS5LF5x887x422x0 1t29g4n 192.168.40.83,127.0.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.plugin.osgi.factory.OsgiPlugin Unable to start the plugin container for plugin 'se.bjurr.changelog.git-changelog-for-bitbucket'
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'changelogLibService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Unsatisfied dependency expressed through constructor argument with index 3 of type [se.bjurr.changelog.bitbucket.application.JiraClientService]: : Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:325) ~[na:na]
        at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85) ~[na:na]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:290) ~[na:na]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
        ... 11 frames trimmed
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_74]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
        at se.bjurr.gitchangelog.internal.integrations.jira.JiraClient.<init>(JiraClient.java:13) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService$1.<init>(JiraClientService.java:20) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService.<clinit>(JiraClientService.java:20) ~[na:na]
        ... 10 common frames omitted
2016-07-25 14:47:43,635 WARN  [http-nio-7990-exec-3] asuda @1WS5LF5x887x495x1 1t29g4n 192.168.40.83,127.0.0.1 "GET /rest/plugins/1.0/available/se.bjurr.changelog.git-changelog-for-bitbucket-key/review HTTP/1.1" c.a.u.p.MarketplaceReviewsAndNotificationsServiceImpl Marketplace returned error 401 when getting review at https://marketplace.atlassian.com/rest/2/addons/se.bjurr.changelog.git-changelog-for-bitbucket/reviews/mine
2016-07-25 14:47:50,848 ERROR [ThreadPoolAsyncTaskExecutor::Thread 45] asuda @1WS5LF5x887x422x0 1t29g4n 192.168.40.83,127.0.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" o.e.g.b.e.i.u.c.RunnableTimedExecution Closing runnable for context NonValidatingOsgiBundleXmlApplicationContext(bundle=se.bjurr.changelog.git-changelog-for-bitbucket, config=osgibundle:/META-INF/spring/*.xml) did not finish in 10000ms; consider taking a snapshot and then shutdown the VM in case the thread still hangs
2016-07-25 14:47:50,894 ERROR [ThreadPoolAsyncTaskExecutor::Thread 45] asuda @1WS5LF5x887x422x0 1t29g4n 192.168.40.83,127.0.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" o.e.g.b.e.i.s.ExtenderConfiguration Application context refresh failed (NonValidatingOsgiBundleXmlApplicationContext(bundle=se.bjurr.changelog.git-changelog-for-bitbucket, config=osgibundle:/META-INF/spring/*.xml))
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'changelogLibService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Unsatisfied dependency expressed through constructor argument with index 3 of type [se.bjurr.changelog.bitbucket.application.JiraClientService]: : Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[org.apache.servicemix.bundles.spring-beans-4.1.7.RELEASE_1.jar:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:60) ~[gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:325) ~[gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85) ~[na:na]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:290) ~[gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137) [gemini-blueprint-extender-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
        ... 11 frames trimmed
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275) ~[org.apache.servicemix.bundles.spring-beans-4.1.7.RELEASE_1.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_74]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[org.apache.servicemix.bundles.spring-beans-4.1.7.RELEASE_1.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
        at se.bjurr.gitchangelog.internal.integrations.jira.JiraClient.<init>(JiraClient.java:13) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService$1.<init>(JiraClientService.java:20) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService.<clinit>(JiraClientService.java:20) ~[na:na]
        ... 10 common frames omitted
2016-07-25 14:47:50,901 ERROR [ThreadPoolAsyncTaskExecutor::Thread 45] asuda @1WS5LF5x887x422x0 1t29g4n 192.168.40.83,127.0.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" o.e.g.b.e.i.d.s.DependencyWaiterApplicationContextExecutor Unable to create application context for [se.bjurr.changelog.git-changelog-for-bitbucket], unsatisfied dependencies: none
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'changelogLibService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Unsatisfied dependency expressed through constructor argument with index 3 of type [se.bjurr.changelog.bitbucket.application.JiraClientService]: : Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:325) ~[na:na]
        at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85) ~[na:na]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:290) ~[na:na]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
        ... 11 frames trimmed
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraClientService' defined in URL [bundle://126.0:0/META-INF/spring/atlassian-plugins-components.xml]: Bean instantiation via constructor failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_74]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
        at se.bjurr.gitchangelog.internal.integrations.jira.JiraClient.<init>(JiraClient.java:13) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService$1.<init>(JiraClientService.java:20) ~[na:na]
        at se.bjurr.changelog.bitbucket.application.JiraClientService.<clinit>(JiraClientService.java:20) ~[na:na]
        ... 10 common frames omitted
```

**Comment by BrunoLavitForgerock** [comment]
Hi,
We are using Bitbucket 4.5.1 and I'm getting the same error after the upgrade to the 1.10 version.
Thanks in advance for a fix :)

**Comment by tomasbjerre** [comment]
Should be fixed now, open issue again if not working!
